apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "generic-service.fullname" . }}
  labels:
    app: {{ template "generic-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  #serviceAccountName: {{ default "default" .Values.serviceAccountNameOverride | quote }}
  selector:
    matchLabels:
      app: {{ template "generic-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "generic-service.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
      annotations:
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      containers:
        - name: {{  template "generic-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.workingDir }}
          workingDir: {{ .Values.workingDir }}
          {{- end }}
          {{- if .Values.command }}
          command:
{{ toYaml .Values.command | indent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
{{ toYaml .Values.args | indent 12 }}
          {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle:
{{ toYaml .Values.lifecycle | indent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.extraEnvValues }}
            {{- range $key, $value := .Values.extraEnvValues }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end -}}
            {{- end -}}
            {{- if .Values.extraEnv }}
            {{ toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.service.enabled }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.data.enabled }}
          - name: data
            mountPath: {{ .Values.data.mountPath }}
            {{- if and .Values.data.persistence.enabled .Values.data.persistence.subPath }}
            subPath: {{ .Values.data.persistence.subPath }}
            {{- end }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
          {{- end }}
      volumes:
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
      {{- end }}
        {{- if .Values.config }}
        - name: config-volume
          configMap:
            name: {{ template "generic-service.fullname" . }}
        {{- end }}
        {{- if .Values.data.enabled }}
        - name: data
          {{- if and .Values.data.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.data.persistence.existingClaim }}
            claimName: {{ .Values.data.persistence.existingClaim }}
            {{- else }}
            claimName: {{ template "generic-service.fullname" . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
