apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "generic-service.name" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "generic-service.name" . }}
      release: {{ .Release.Name }}
